#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo "Updating personal formulae..."

brew bundle --file=- <<EOF

# zsh
brew "zplug"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "diff-so-fancy"
brew "exa"

EOF