#!/bin/sh

# set -e
shopt -s dotglob

# Add local psqlrc
if [ ! -f "$HOME"/.local/psqlrc ]; then
  touch ~/.local/psqlrc
fi

# Upgrade Vim plugins
if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa -

reset -Q

# Symlink Vim plugins to Neovim
for dir in "$HOME"/.vim/*; do
  if [ -d "$dir" ]; then
    directory_name=$(basename "$dir")

    if [ ! -e "$HOME"/.config/nvim/"$directory_name" ]; then
      ln -sf "$dir" "$HOME"/.config/nvim/"$directory_name"
    fi
  fi
done


# Ensure fzf is present
if [ ! -d "$HOME"/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME"/.fzf
  "$HOME"/.fzf/install
fi

# Detect old macOS broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}
(called from ${dir}/post-up:${LINENO})
MSG
fi
